[tools]
python = "3.10"
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[hooks]
postinstall = "mise x -- uv sync"

[tasks.check]
run = ["uv sync", "black --check .", "ruff check", "mypy", "pytest"]
