[tools]
python = "3.10"
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[hooks]
postinstall = "uv sync"

[tasks.check]
run = ["black --check .", "ruff check", "mypy", "pytest"]

[tasks.fix]
run = ["black .", "ruff check --fix", "mypy", "pytest"]
